
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_BASE_URL_WEBSOCKET_CHAT
ARG VITE_BASE_URL_WEBSOCKET_CONTACTS
ARG VITE_BASE_URL_USER
ARG VITE_BASE_URL
ARG VITE_USER_SERVICE_URL
ARG VITE_AUTH_SERVICE_URL
ARG VITE_CHAT_SERVICE_URL
ARG VITE_CONTACTS_SERVICE_URL
ARG VITE_INVITATION_SERVICE_URL
ARG VITE_MAIL_SERVICE_URL

ENV VITE_BASE_URL_WEBSOCKET_CHAT=${VITE_BASE_URL_WEBSOCKET_CHAT}
ENV VITE_BASE_URL_WEBSOCKET_CONTACTS=${VITE_BASE_URL_WEBSOCKET_CONTACTS}
ENV VITE_BASE_URL_USER=${VITE_BASE_URL_USER}
ENV VITE_BASE_URL=${VITE_BASE_URL}
ENV VITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}
ENV VITE_AUTH_SERVICE_URL=${VITE_AUTH_SERVICE_URL}
ENV VITE_CHAT_SERVICE_URL=${VITE_CHAT_SERVICE_URL}
ENV VITE_CONTACTS_SERVICE_URL=${VITE_CONTACTS_SERVICE_URL}
ENV VITE_INVITATION_SERVICE_URL=${VITE_INVITATION_SERVICE_URL}
ENV VITE_MAIL_SERVICE_URL=${VITE_MAIL_SERVICE_URL}

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080 443

# Container çalışınca nginx başlasın
CMD ["nginx", "-g", "daemon off;"]
