
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_BASE_URL_WEBSOCKET_CHAT
ARG VITE_BASE_URL_WEBSOCKET_CONTACTS
ARG VITE_BASE_URL_USER
ARG VITE_BASE_URL
ARG VITE_USER_SERVICE_URL
ARG VITE_AUTH_SERVICE_URL
ARG VITE_CHAT_SERVICE_URL
ARG VITE_CONTACTS_SERVICE_URL
ARG VITE_INVITATION_SERVICE_URL
ARG VITE_MAIL_SERVICE_URL

ENV VITE_BASE_URL_WEBSOCKET_CHAT=${VITE_BASE_URL_WEBSOCKET_CHAT}
ENV VITE_BASE_URL_WEBSOCKET_CONTACTS=${VITE_BASE_URL_WEBSOCKET_CONTACTS}
ENV VITE_BASE_URL_USER=${VITE_BASE_URL_USER}
ENV VITE_BASE_URL=${VITE_BASE_URL}
ENV VITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}
ENV VITE_AUTH_SERVICE_URL=${VITE_AUTH_SERVICE_URL}
ENV VITE_CHAT_SERVICE_URL=${VITE_CHAT_SERVICE_URL}
ENV VITE_CONTACTS_SERVICE_URL=${VITE_CONTACTS_SERVICE_URL}
ENV VITE_INVITATION_SERVICE_URL=${VITE_INVITATION_SERVICE_URL}
ENV VITE_MAIL_SERVICE_URL=${VITE_MAIL_SERVICE_URL}

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf


CMD ["nginx", "-g", "daemon off;"]



# -------------------
# Build Stage
# -------------------
# FROM node:20-alpine AS build
# WORKDIR /app

# # Package dosyalarını kopyala ve bağımlılıkları yükle
# COPY package*.json ./
# RUN npm install

# # Tüm kaynak kodu kopyala
# COPY . .

# # Build argümanlarını tanımla
# ARG VITE_BASE_URL_WEBSOCKET_CHAT
# ARG VITE_BASE_URL_WEBSOCKET_CONTACTS
# ARG VITE_BASE_URL_USER
# ARG VITE_BASE_URL
# ARG VITE_USER_SERVICE_URL
# ARG VITE_AUTH_SERVICE_URL
# ARG VITE_CHAT_SERVICE_URL
# ARG VITE_CONTACTS_SERVICE_URL
# ARG VITE_INVITATION_SERVICE_URL
# ARG VITE_MAIL_SERVICE_URL

# # ENV olarak da build stage’de tanımla
# ENV VITE_BASE_URL_WEBSOCKET_CHAT=${VITE_BASE_URL_WEBSOCKET_CHAT}
# ENV VITE_BASE_URL_WEBSOCKET_CONTACTS=${VITE_BASE_URL_WEBSOCKET_CONTACTS}
# ENV VITE_BASE_URL_USER=${VITE_BASE_URL_USER}
# ENV VITE_BASE_URL=${VITE_BASE_URL}
# ENV VITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}
# ENV VITE_AUTH_SERVICE_URL=${VITE_AUTH_SERVICE_URL}
# ENV VITE_CHAT_SERVICE_URL=${VITE_CHAT_SERVICE_URL}
# ENV VITE_CONTACTS_SERVICE_URL=${VITE_CONTACTS_SERVICE_URL}
# ENV VITE_INVITATION_SERVICE_URL=${VITE_INVITATION_SERVICE_URL}
# ENV VITE_MAIL_SERVICE_URL=${VITE_MAIL_SERVICE_URL}

# # Uygulamayı build et
# RUN npm run build

# # -------------------
# # Production Stage
# # -------------------
# FROM node:20-alpine
# WORKDIR /app

# # serve paketini yükle
# RUN npm install -g serve

# # Build stage’den dist klasörünü kopyala
# COPY --from=build /app/dist ./dist

# # Aynı ARG’leri production stage’de de tanımla
# ARG VITE_BASE_URL_WEBSOCKET_CHAT
# ARG VITE_BASE_URL_WEBSOCKET_CONTACTS
# ARG VITE_BASE_URL_USER
# ARG VITE_BASE_URL
# ARG VITE_USER_SERVICE_URL
# ARG VITE_AUTH_SERVICE_URL
# ARG VITE_CHAT_SERVICE_URL
# ARG VITE_CONTACTS_SERVICE_URL
# ARG VITE_INVITATION_SERVICE_URL
# ARG VITE_MAIL_SERVICE_URL

# # ENV olarak production stage’de de tanımla
# ENV VITE_BASE_URL_WEBSOCKET_CHAT=${VITE_BASE_URL_WEBSOCKET_CHAT}
# ENV VITE_BASE_URL_WEBSOCKET_CONTACTS=${VITE_BASE_URL_WEBSOCKET_CONTACTS}
# ENV VITE_BASE_URL_USER=${VITE_BASE_URL_USER}
# ENV VITE_BASE_URL=${VITE_BASE_URL}
# ENV VITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}
# ENV VITE_AUTH_SERVICE_URL=${VITE_AUTH_SERVICE_URL}
# ENV VITE_CHAT_SERVICE_URL=${VITE_CHAT_SERVICE_URL}
# ENV VITE_CONTACTS_SERVICE_URL=${VITE_CONTACTS_SERVICE_URL}
# ENV VITE_INVITATION_SERVICE_URL=${VITE_INVITATION_SERVICE_URL}
# ENV VITE_MAIL_SERVICE_URL=${VITE_MAIL_SERVICE_URL}

# EXPOSE 8080
# CMD ["serve", "-s", "dist", "-l", "8080"]



